### ISSUE TITLE
sim: 整数レジスタと浮動小数点数レジスタを別々にダンプする

### ISSUE THREAD

**Issue by zeptometer** [ProcessorCompilerExperiment2014-Team0/Zekamashi#4]
今考えているZekamashiのパイプラインでは計算結果がレジスタに書き込まれるタイミングが整数レジスタか浮動小数点数レジスタかによって異なってくるためレジスタのダンプを別々にしてもらうと好都合です。

* -r filename  : filenameに命令毎の整数レジスタの内容を出力する
* -f filename  : filenameに命令毎の浮動小数点数レジスタの内容を出力する

**Comment by minus3theta** [comment]
既存の-rを残すため、-ir、-frオプションとしました
PCとレジスタの値を出力します
filenameを指定しない場合のデフォルトはそれぞれ"hoge.ilog"、"hoge.flog"

**Comment by zeptometer** [comment]
了解ありがとう:)
